# SPDX-FileCopyrightText: 2020 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
    - name: Reuse
      run: |
          ~/.local/bin/reuse lint
    - name: Doc8
      run: |
          ~/.local/bin/doc8
