# SPDX-FileCopyrightText: 2020 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: reference|LICENSES

repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
   - id: clang-format

- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
  - id: black
    args: ['--line-length=79']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: check-xml
  - id: check-yaml
  - id: check-case-conflict
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
    args: ['--maxkb=800']

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8

- repo: https://github.com/pycqa/doc8
  rev: v1.1.1
  hooks:
  - id: doc8

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/fsfe/reuse-tool
  rev: v2.1.0
  hooks:
  - id: reuse

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format

- repo: local
  hooks:
  - id: sphinx
    name: sphinx
    entry: make spelling html latexpdf linkcheck 
    language: system
    pass_filenames: false
    always_run: true
