# SPDX-FileCopyrightText: 2020 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          python3 -m venv venv
	  . venv/bin/activate
          pip install --quiet --upgrade pip wheel
          pip install --quiet -r requirements.txt
    - name: Sphinx
      run: |
          python doc.py html
    - name: Reuse
      run: |
          reuse lint
    - name: Doc8
      run: |
          doc8
    - name: Black
      run: |
          black --skip-string-normalization --line-length 79 --check .
    - name: Flake8
      run: |
          flake8
    - name: clang-format
      run: |
          find . -name '*.cpp' | xargs clang-format -i
	  git diff --exit-code
