# SPDX-FileCopyrightText: 2020 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          sudo apt-get update -qq
          DEBIAN_FRONTEND=noninteractive xargs -a ubuntu-packages.txt sudo apt-get install -qq
          python3 -m venv venv
          . venv/bin/activate
          sudo -H python3 -m pip install --quiet --upgrade pip wheel setuptools
          sudo -H python3 -m pip install --quiet --upgrade -r requirements.txt
    - name: Sphinx
      run: |
          python3 doc.py html
    - name: Doc8
      run: |
          doc8 --ignore-path venv
    - name: Black
      run: |
          black --exclude venv --skip-string-normalization --line-length 79 --check .
    - name: Flake8
      run: |
          flake8 --exclude venv
    - name: clang-format
      run: |
          find source -name '*.cpp' | xargs clang-format -i
          git diff --exit-code
    - name: Reuse
      run: |
          reuse lint
