# SPDX-FileCopyrightText: 2020 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: checks

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive xargs -a ubuntu-packages.txt apt-get install -qq
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --quiet --upgrade pip wheel
          python -m pip install --quiet --upgrade -r requirements.txt
    - name: Sphinx
      run: |
          . venv/bin/activate
          python doc.py html
    - name: Doc8
      run: |
          . venv/bin/activate
          doc8 --ignore-path venv
    - name: Black
      run: |
          . venv/bin/activate
          black --exclude venv --skip-string-normalization --line-length 79 --check .
    - name: Flake8
      run: |
          . venv/bin/activate
          flake8 --exclude venv
    - name: clang-format
      run: |
          find source -name '*.cpp' | xargs clang-format -i
          git diff --exit-code
    - name: Reuse
      run: |
          . venv/bin/activate
          which reuse
          reuse --version
          reuse lint
