# SPDX-FileCopyrightText: 2024 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: Checks

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Checks
      uses: pre-commit/action@v3.0.0
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docs
        path: build

  icpx:
    runs-on: ubuntu-latest
    env:
        CXX: icpx
    steps:
    - uses: actions/checkout@v4
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: |
          icx@2023.2.1
    - name: Build Examples
      run: |
        source /opt/intel/oneapi/setvars.sh
        cd source/examples
        cmake -B build
        make -j 2 -C build
        ctest --test-dir build --label-exclude gpu
